fix ios bug with screensize
testdevlab/cv_pom pull request #24
Opened 2024-07-29 08:33 UTC by alvarolaserna

closes #23

2024-07-30 07:26 UTC, EinarsNG reviewed
Couple of microscopic typing changes. Apart from that all good.

2024-08-06 07:21 UTC, raulbmejias requested changes

2024-08-06 07:21 UTC, raulbmejias commented on cv_pom/frameworks/testui.py
> +            mouse=PointerInput(interaction.POINTER_TOUCH, "touch"),
This part of the code, looks like, doesn't have the right formatter . There are more part of the code with the same problem.

2024-08-23 04:38 UTC, alvarolaserna commented on cv_pom/frameworks/testui.py
> +            mouse=PointerInput(interaction.POINTER_TOUCH, "touch"),
why do you say so? I dont see any difference

2024-08-26 10:42 UTC, raulbmejias commented on cv_pom/frameworks/testui.py
> +            mouse=PointerInput(interaction.POINTER_TOUCH, "touch"),
The right format should be: (space between "=")
`
mouse = PointerInput(interaction.POINTER_TOUCH, "touch"),`
shouldn't be?
There are other part of the code with that.

2024-09-16 07:10 UTC, raulbmejias commented on cv_pom/frameworks/testui.py
> +            mouse=PointerInput(interaction.POINTER_TOUCH, "touch"),
Yap, it's a bit confusing but you are right.

2024-09-16 07:11 UTC, raulbmejias approved these changes

2024-09-16 07:16 UTC, merged